apiVersion: v1
stringData:
  DEPLOY_ENV: 'qa'
  PORT: '8090'
  MONGO_URL: "mongodb://account:password@127.0.0.1:27017/task-schedule?authSource=admin&replicaSet=rs-mongo-replica-59e61d5cdca3&retryWrites=true"
  REDIS_URL: "redis://127.0.0.1:6379"
  REDIS_PWD: "wvMn4OBlhXuCJ68VK"
  REDIS_DB: '1'
  REDIS_PREFIX: 'task_schedule_qa'
  INSTANCES: '2'
  LOG_LEVEL: 'info'
  NO_COLOR: '1'
  # log
  LOG_FILE_ENABLED: 'true'
  # MQ
  DISABLE_MQ_CONSUMER: '0'
  # Pulsar
  PULSAR_SERVICE_URL: "http://127.0.0.1:8080"
  PULSAR_TOKEN: "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzZi1yeSJ9.ckFNXB3jALMblB1YdosmECX-07mlGLxcU1F16m47w9M"
  PULSAR_OPERATION_TIMEOUT_SECONDS: "30"
  DEFAULT_CONSUMER_SUBSCRIPTION: "task-schedule-consumer"
  PULSAR_NAMESPACE: "social-x"
  PULSAR_CLUSTER: "socialflow"
  SUBSCRIPTION_INIT_POSITION: 'Earliest'
  # trace
  IS_TRACE_ON: "1"
  TRACE_GRPC_ENDPOINT: "http://127.0.0.1:4317"
  TRACE_APP_KEY: "76d5850a45785d3ed333ea7a518fb6ed"
  TRACE_SERVICE_NAME: "task_schedule_qa"
kind: Secret
metadata:
  name: cm-task-schedule
  namespace: socialflow-ry
type: Opaque
